from __future__ import annotations

from simulation_core.fluids import (
    CG_PRECONDITIONER_CHOICES,
    CartesianFluidSolver,
    CartesianGrid,
    FluidDomainSpec,
    FluidImpulseReport,
    ForceSpreadingReport,
    GradedGridSpec,
    HIBM_PRESSURE_COMPONENT_CAPACITY,
    HIBM_TINY_UNREACHED_COMPONENT_CLEANUP_THRESHOLD_CELLS,
    HIBM_UNREACHED_COMPONENT_SMALL_THRESHOLD_CELLS,
    PRESSURE_OUTLET_AUTO_CLEANUP_ACCEPTANCE_MARGIN,
    PRESSURE_OUTLET_AUTO_CLEANUP_MAX_PASSES,
    PRESSURE_OUTLET_AUTO_CLEANUP_MIN_L2,
    PRESSURE_OUTLET_AUTO_CLEANUP_NO_REGRESSION_MARGIN,
    PRESSURE_OUTLET_AUTO_CLEANUP_TARGET_REDUCTION,
    RefinementRegion,
    VelocityConstraintReport,
    VelocityDirichletBoundaryReport,
    build_graded_grid,
    pressure_outlet_cleanup_iteration_budget,
)

__all__ = [
    "CG_PRECONDITIONER_CHOICES",
    "CartesianFluidSolver",
    "CartesianGrid",
    "FluidDomainSpec",
    "FluidImpulseReport",
    "ForceSpreadingReport",
    "GradedGridSpec",
    "HIBM_PRESSURE_COMPONENT_CAPACITY",
    "HIBM_TINY_UNREACHED_COMPONENT_CLEANUP_THRESHOLD_CELLS",
    "HIBM_UNREACHED_COMPONENT_SMALL_THRESHOLD_CELLS",
    "PRESSURE_OUTLET_AUTO_CLEANUP_ACCEPTANCE_MARGIN",
    "PRESSURE_OUTLET_AUTO_CLEANUP_MAX_PASSES",
    "PRESSURE_OUTLET_AUTO_CLEANUP_MIN_L2",
    "PRESSURE_OUTLET_AUTO_CLEANUP_NO_REGRESSION_MARGIN",
    "PRESSURE_OUTLET_AUTO_CLEANUP_TARGET_REDUCTION",
    "RefinementRegion",
    "VelocityConstraintReport",
    "VelocityDirichletBoundaryReport",
    "build_graded_grid",
    "pressure_outlet_cleanup_iteration_budget",
]
