from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


SYNTHETIC_SOURCE = "synthetic-test-only-not-fluent-truth"


def build_synthetic_fluent_reference_fixture(
    output_dir: Path,
    *,
    force_z_n: float = 2.0,
) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written = {
        "tip_displacement": _write_csv(
            output_dir / "fluent_tip_displacement_history.csv",
            [
                "step",
                "time_s",
                "tip_displacement_x_m",
                "tip_displacement_y_m",
                "tip_displacement_z_m",
                "tip_displacement_norm_m",
                "max_displacement_m",
                "source",
            ],
            {
                "step": 50,
                "time_s": 0.025,
                "tip_displacement_x_m": 0.0,
                "tip_displacement_y_m": 0.0,
                "tip_displacement_z_m": 0.01,
                "tip_displacement_norm_m": 0.01,
                "max_displacement_m": 0.02,
                "source": SYNTHETIC_SOURCE,
            },
        ),
        "force": _write_csv(
            output_dir / "fluent_force_history.csv",
            [
                "step",
                "time_s",
                "force_x_N",
                "force_y_N",
                "force_z_N",
                "primary_force_z_N",
                "secondary_force_z_N",
                "source",
            ],
            {
                "step": 50,
                "time_s": 0.025,
                "force_x_N": 0.0,
                "force_y_N": 0.0,
                "force_z_N": force_z_n,
                "primary_force_z_N": force_z_n / 2.0,
                "secondary_force_z_N": force_z_n / 2.0,
                "source": SYNTHETIC_SOURCE,
            },
        ),
        "flow": _write_csv(
            output_dir / "fluent_flow_balance_history.csv",
            [
                "step",
                "time_s",
                "inlet_flow_rate_m3s",
                "outlet_flow_rate_m3s",
                "pressure_outlet_flux_m3s",
                "velocity_outlet_flux_m3s",
                "source",
            ],
            {
                "step": 50,
                "time_s": 0.025,
                "inlet_flow_rate_m3s": 0.001,
                "outlet_flow_rate_m3s": 0.001,
                "pressure_outlet_flux_m3s": 0.001,
                "velocity_outlet_flux_m3s": 0.001,
                "source": SYNTHETIC_SOURCE,
            },
        ),
        "pressure": _write_csv(
            output_dir / "fluent_pressure_summary_history.csv",
            [
                "step",
                "time_s",
                "pressure_min_pa",
                "pressure_max_pa",
                "pressure_range_pa",
                "source",
            ],
            {
                "step": 50,
                "time_s": 0.025,
                "pressure_min_pa": 100.0,
                "pressure_max_pa": 160.0,
                "pressure_range_pa": 60.0,
                "source": SYNTHETIC_SOURCE,
            },
        ),
        "metadata": _write_metadata(output_dir / "fluent_metadata_2026-06-28.md"),
        "public_evidence": _write_public_evidence(
            output_dir / "public_tutorial_evidence_map.json"
        ),
    }
    return written


def _write_csv(path: Path, header: list[str], row: dict[str, Any]) -> str:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=header)
        writer.writeheader()
        writer.writerow(row)
    return path.as_posix()


def _write_metadata(path: Path) -> str:
    lines = [
        "# Synthetic Fluent Reference Metadata",
        "",
        "- Source document: synthetic test fixture, not Fluent truth",
        "- Fluent run id: synthetic-test-only",
        "- Export author: synthetic-test",
        "- Export date: 2026-06-29",
        "- Fluent version: synthetic-test-only",
        "- mesh/domain source: synthetic lower-symmetry-half domain",
        "- geometry units: m",
        "- material model: synthetic air and linear elastic flap",
        "- boundary conditions: synthetic ANSYS vertical-flap FSI setup",
        "- time step: 0.0005",
        "- number of steps: 50",
        "- coupling settings if applicable: synthetic two-way FSI fixture",
        "- export procedure: generated by build_synthetic_fluent_reference_fixture.py",
        "- who/when/how generated: synthetic test fixture generated in temp directory",
        "- force_z_positive: positive z matches source-step marker force",
        "- flow_rate_positive: positive zmin outlet flow leaves the domain",
        "- pressure_reference: synthetic gauge pressure relative to pressure outlet",
        "- displacement_definition: synthetic flap tip total displacement",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path.as_posix()


def _write_public_evidence(path: Path) -> str:
    payload = {
        "case": "ansys_vertical_flap_fsi",
        "evidence_id": "synthetic_public_tutorial_evidence_policy",
        "source_type": "public_tutorial_metadata",
        "use_policy": "metadata_only_not_parity_truth",
        "parity_claim_policy": {
            "fluent_parity_claimed": False,
            "reason": "Synthetic fixture preserves public tutorial metadata boundary.",
        },
    }
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path.as_posix()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--force-z-n", type=float, default=2.0)
    args = parser.parse_args()
    written = build_synthetic_fluent_reference_fixture(
        args.output_dir,
        force_z_n=args.force_z_n,
    )
    print(json.dumps(written, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
