HIBM_OWNER_RELOCATION_WALK_STEPS = 24
HIBM_NO_SLIP_NEAREST_FLUID_FALLBACK_RADIUS_CELLS = 4
HIBM_OVERFLOW_SINGLETON_NO_SLIP_PROTECTION_RADIUS_CELLS = 2
HIBM_TINY_UNREACHED_COMPONENT_CLEANUP_THRESHOLD_CELLS = 4
HIBM_PRESSURE_NEUMANN_NEAREST_FLUID_FALLBACK_RADIUS_CELLS = 2
HIBM_PRESSURE_NEUMANN_ZERO_GRADIENT_TOLERANCE_PA_PER_M = 1.0e-12
HIBM_PRESSURE_DISCONNECTED_SMALL_COMPONENT_THRESHOLD_CELLS = 128
PRESSURE_NEUMANN_INVALID_DIAGNOSTIC_CAPACITY = 1024
PRESSURE_NEUMANN_INVALID_REASON_UNRECONSTRUCTABLE = 1
PRESSURE_NEUMANN_INVALID_REASON_BAD_MARKER = 2
PRESSURE_NEUMANN_INVALID_REASON_NONPOSITIVE_VOLUME = 3
PRESSURE_NEUMANN_INVALID_REASON_NAMES = {
    PRESSURE_NEUMANN_INVALID_REASON_UNRECONSTRUCTABLE: "unreconstructable",
    PRESSURE_NEUMANN_INVALID_REASON_BAD_MARKER: "bad_marker",
    PRESSURE_NEUMANN_INVALID_REASON_NONPOSITIVE_VOLUME: "nonpositive_volume",
}
STRESS_INVALID_REASON_NONE = 0
STRESS_INVALID_REASON_BASE_PRESSURE_MISSING = 1
STRESS_INVALID_REASON_TWO_SIDED_PRESSURE_MISSING = 2
STRESS_INVALID_REASON_VISCOUS_GRADIENT_MISSING = 3
STRESS_INVALID_REASON_NAMES = {
    STRESS_INVALID_REASON_NONE: "none",
    STRESS_INVALID_REASON_BASE_PRESSURE_MISSING: "base_pressure_missing",
    STRESS_INVALID_REASON_TWO_SIDED_PRESSURE_MISSING: "two_sided_pressure_missing",
    STRESS_INVALID_REASON_VISCOUS_GRADIENT_MISSING: "viscous_gradient_missing",
}
